Ass03Solution/eStore/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using BusinessObject.Models;
using DataAccess.Repository;
using System.Threading.Tasks;
using System;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using BusinessObject.Models;

namespace eStore.Controllers
{
    public class OrdersController : Controller
    {
        private readonly Assignment2Context _context;
        IOrderRepository orderRepository;

        public OrdersController(Assignment2Context context)
        {
            _context = context;
            orderRepository = new OrderRepository();
        }

        public IActionResult Index()
        {
            return View();
        }

        // GET: Orders
        public async Task<IActionResult> ViewOrders(DateTime startDate, DateTime endDate)
        {
            var saleManagementContext = _context.Orders.Include(o => o.Member);
            try
            {
                var temp = _context.Orders.Include(o => o.Member).Where(o => o.OrderDate >= startDate && o.OrderDate <= endDate);
                return View(await temp.ToListAsync());
            }
            catch
            {
                
            }
            return View(await saleManagementContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Member)
                //.Include(o => o.MemberId == id)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }
            //return View(order);
            return RedirectToAction("OrderDetails.cshtml", order.OrderId);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,MemberId,OrderDate,RequiredDate,ShippedDate,Freight")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ViewOrders));
            }
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", order.MemberId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", order.MemberId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,MemberId,OrderDate,RequiredDate,ShippedDate,Freight")] Order order)
        {
            if (id != order.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ViewOrders));
            }
            ViewData["MemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", order.MemberId);
            return View(order);
        }

        //GET: Products/Delete/5
        public ActionResult Delete(int id)
        {
            var order = orderRepository.GetOrderById(id);
            if(order == null)
            {
                return NotFound();
            }
            orderRepository.Remove(id);
            return RedirectToAction(nameof(ViewOrders));
        }
        //public ActionResult Delete(int id)
        //{
        //    var order = orderRepository.GetOrderById(id);
        //    if (order == null)
        //    {
        //        return NotFound();
        //    }
        //    orderRepository.Remove(id);
        //    return RedirectToAction(nameof(ViewOrders));
        //}

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, IFormCollection collection)
        {
            //var order = await _context.Orders.FindAsync(id);
            //_context.Orders.Remove(order);
            //await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(ViewOrders));
            try
            {
                return RedirectToAction(nameof(ViewOrders));
            }
            catch
            {
                return View();
            }
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.OrderId == id);
        }
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(ViewOrders));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

Ass03Solution/eStore/Views/Orders/Create.cshtml
@model BusinessObject.Models.Order;

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MemberId" class="control-label"></label>
                <select asp-for="MemberId" class ="form-control" asp-items="ViewBag.MemberId"></select>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequiredDate" class="control-label"></label>
                <input asp-for="RequiredDate" class="form-control" />
                <span asp-validation-for="RequiredDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippedDate" class="control-label"></label>
                <input asp-for="ShippedDate" class="form-control" />
                <span asp-validation-for="ShippedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Freight" class="control-label"></label>
                <input asp-for="Freight" class="form-control" />
                <span asp-validation-for="Freight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ViewOrders">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ass03Solution/eStore/Views/Orders/Delete.cshtml
@model BusinessObject.Models.Order;

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequiredDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequiredDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShippedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShippedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Freight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Freight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Member.MemberId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="ViewOrders">Back to List</a>
    </form>
</div>

Ass03Solution/eStore/Views/Orders/Details.cshtml
@model BusinessObject.Models.Order

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequiredDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequiredDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShippedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShippedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Freight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Freight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Member.MemberId)
        </dd>
    </dl>
</div>
<div>
  @*  <a asp-action="Edit" asp-route-id="@Model.OrderId">Edit</a> |*@
    <a asp-action="Edit" >Edit</a> |
    <a asp-action="ViewOrders">Back to List</a>
</div>

Ass03Solution/eStore/Views/Orders/Edit.cshtml
@model BusinessObject.Models.Order
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderId" />
            <div class="form-group">
                <label asp-for="MemberId" class="control-label"></label>
                <select asp-for="MemberId" class="form-control" asp-items="ViewBag.MemberId"></select>
                <span asp-validation-for="MemberId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequiredDate" class="control-label"></label>
                <input asp-for="RequiredDate" class="form-control" />
                <span asp-validation-for="RequiredDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippedDate" class="control-label"></label>
                <input asp-for="ShippedDate" class="form-control" />
                <span asp-validation-for="ShippedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Freight" class="control-label"></label>
                <input asp-for="Freight" class="form-control" />
                <span asp-validation-for="Freight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ViewOrders">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ass03Solution/eStore/Views/Orders/ViewOrders.cshtml
@model IEnumerable<BusinessObject.Models.Order>


@{
    ViewData["Title"] = "Index";
}

<h1>Order Management</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Orders" asp-action="ViewOrders">
    <p><span>From date: </span><input type="datetime-local" id="date" name="startDate" value="@DateTime.Today.ToString()" /></p>
    <p><span>To date: </span><input type="datetime-local" id="date" name="endDate" value="@DateTime.Today.ToString()" /></p>
    <input type="submit" value="Filter" />
</form>

@{
    if(TempData.Peek("Messsage") != null)
    {
        <h3>@TempData.Peek("Message")</h3>
    }
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequiredDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShippedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Freight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MemberId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequiredDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ShippedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Freight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MemberId)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.OrderId">Edit</a> |
                    <a asp-controller="OrderDetails" asp-action="OrderDetails" asp-route-id="@item.OrderId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.OrderId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>